#'Some BullShit
#'
#'
plotsPoly<-function(fn_rst,
                    fn_xmin,
                    fn_xmax,
                    fn_ymin,
                    fn_ymax,
                    fn_plcn,
                    fn_plc,
                    fn_plcRange,
                    fn_xaxs,
                    fn_yaxs,
                    fn_xaxt,
                    fn_yaxt,
                    fn_colNA,
                    fn_Bx,fn_By,
                    fn_bgc,
                    fn_geom,
                    fn_geomB,
                    fn_title){
  plot(fn_rst,
       xlim=c(fn_xmin,
              fn_xmax),
       ylim=c(fn_ymin,
              fn_ymax),
       col=fn_plc(fn_plcn),
       breaks=fn_plcRange,
       asp=1,
       xaxs=fn_xaxs,
       yaxs=fn_yaxs,
       xaxt=fn_xaxt,
       yaxt=fn_yaxt,
       legend=F,
       colNA=fn_colNA)
  points(x=fn_Bx,y=fn_By,
         pch=21,
         bg=fn_bgc)
  plot(fn_geom,
       border=fn_geomB,
       add=T)
  title(fn_title,adj=0,line=0.3)
}
